# Generated by Django 4.1 on 2026-02-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_1', models.CharField(max_length=100)),
                ('attribute_2', models.TextField()),
            ],
            options={
                'db_table': 'sample_tb',
            },
        ),
        migrations.CreateModel(
            name='TextRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
